# docker-compose.yml
version: '2.2'

networks:
  app-network:
    name: docker-network
    driver: bridge

services:
  noithatlucmo_db:
    container_name: noithatlucmo_db
    command:
      --default-authentication-plugin=mysql_native_password
      --secure-file-priv=""
    restart: unless-stopped
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootducdv@79
      - MYSQL_DATABASE=noithatlucmo
      - MYSQL_USER=ducdv79
      - MYSQL_PASSWORD=ducdv@79
      - SERVICE_NAME=mysql
      - SERVICE_TAGS=dev
    ports:
      - 3307:3306
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - noithatlucmo_db:/var/lib/mysql
    networks:
      - app-network

  noithatlucmo_app:
    container_name: noithatlucmo_app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - .:/app
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - noithatlucmo_db
    environment:
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_HOST=noithatlucmo_db
      - DB_DATABASE=noithatlucmo
      - DB_USERNAME=ducdv79
      - DB_PASSWORD=ducdv@79
    networks:
      - app-network

volumes:
  noithatlucmo_db:
    driver: local
